spring.application.name=inventory-api

spring.datasource.url=jdbc:postgresql://localhost:5432/localinventory
spring.datasource.username=postgres
spring.datasource.password=Mom@2512

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=3f8a2b1c9d4e7f6a0b5c8d2e1f4a7b3c9d6e2f5a8b1c4d7e0f3a6b9c2d5e8f1
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger-ui.html